name: adabank
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  firebase_auth: ^5.3.4
  firebase_core: ^3.9.0
  fl_chart: ^0.69.2
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.16
  get: ^4.6.6
  get_storage: ^2.1.1
  google_fonts: ^6.2.1
  intl: ^0.20.1
  mobile_scanner: ^6.0.2
  page_transition: ^2.1.0
  persistent_bottom_nav_bar: ^6.2.1
  pin_code_fields: ^8.0.1
  pretty_qr_code: ^3.3.0
  swipeable_button_view: ^0.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/svg/